[project]
name = "django-ai-agent"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.3",
    "jupyter>=1.1.1",
    "langchain-openai>=0.3.23",
    "langgraph>=0.4.8",
    "permit>=2.7.5",
    "python-decouple>=3.8",
]
