# Generated by Django 5.2.3 on 2025-06-15 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="active_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
