# Generated by Django 5.2.3 on 2025-06-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_active_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="active_at",
            field=models.DateTimeField(null=True),
        ),
    ]
